spring.application.name=ecommerce-api

# Configuração do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:matutadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza as tabelas automaticamente e mostra o SQL no log
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (Para acessar o painel do banco pela URL)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Recursos estáticos
spring.web.resources.static-locations=classpath:/static/

# Configurações do Cloudinary para Upload Permanente de Imagens
cloudinary.cloud_name=fqy9ixya
cloudinary.api_key=859655423584782
cloudinary.api_secret=krOMX6ep9Ln4Olg7CWUPBGFhsHY