spring.application.name=ecommerce-api

# Configuração do Banco de Dados H2 em Memória (Roda interno sem precisar de Wamp)
spring.datasource.url=jdbc:h2:mem:matutadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mapeamento para salvar as fotos na sua pasta física
spring.web.resources.static-locations=classpath:/static/,file:///C:/Users/rober/IdeaProjects/midias/imagens-boutique/ng.jpa.show-sql=true